CasaCodigoVS/CasaCodigoVS/Models/ErrorViewModel.cs
using System;

namespace CasaCodigoVS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CasaCodigoVS/CasaCodigoVS/Models/ItemPedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CasaCodigoVS.Models
{
  public class ItemPedido
  {
    public int Id { get; private set; }
    public Produto Produto { get; private set; }
    public int Quantidade { get; private set; }
    public decimal PrecoUnitario { get; private set; }
    public decimal Subtotal
    {
      get
      {
        return Quantidade * PrecoUnitario;
      }
    }

    public ItemPedido(int id, Produto produto, int quantidade, decimal precoUnitario)
    {
      Id = id;
      Produto = produto;
      Quantidade = quantidade;
      PrecoUnitario = precoUnitario;
    }
  }
}

CasaCodigoVS/CasaCodigoVS/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaCodigoVS.Models
{
  public class Produto
  {
    public int Id { get; set; }
    public string Nome { get; set; }
    public decimal Preco { get; set; }

    public Produto(int id, string nome, decimal preco)
    {
      this.Id = id;
      this.Nome = nome;
      this.Preco = preco;
    }
  }
}

CasaCodigoVS/CasaCodigoVS/Models/Produtos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaCodigoVS.Models
{
  public class Produtos
  {
    public int Id { get; set; }
    public string Nome { get; set; }
    public decimal Preco { get; set; }
  }
}

CasaCodigoVS/CasaCodigoVS/Models/ViewModels/CarrinhoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CasaCodigoVS.Models.ViewModels
{
  public class CarrinhoViewModel
  {
    public List<ItemPedido> Itens { get; private set; }
    public decimal Total
    {
      get
      {
        return Itens.Sum(p => p.Subtotal);
      }
    }

    public CarrinhoViewModel(List<ItemPedido> itens)
    {
      Itens = itens;

    }
  }
}

CasaCodigoVS/CasaCodigoVS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CasaCodigoVS.Models;

namespace CasaCodigoVS.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CasaCodigoVS/CasaCodigoVS/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CasaCodigoVS.Models;
using CasaCodigoVS.Models.ViewModels;

namespace CasaCodigoVS.Controllers
{
  public class PedidoController : Controller
  {
    List<Produto> produtos = new List<Produto>
        {
          new Produto(1,"Sleep not found", 59.90M),
          new Produto(2,"May the code be with you", 59.90M),
          new Produto(3,"Rollback", 59.90M),
          new Produto(4,"REST", 69.90M),
          new Produto(5,"Design Patterns com Java", 69.90M),
          new Produto(6,"Vire o jogo com Spring Framework", 69.90M),
          new Produto(7,"Test-Driven Development", 69.90M),
          new Produto(8,"iOS: Programe para iPhone e iPad", 69.90M),
          new Produto(9,"Desenvolvimento de Jogos para Android", 69.90M)
        };

    public IActionResult Carrossel()
    {
      return View(produtos);
    }

    public IActionResult Carrinho()
    {
      return View(GetCarrinhoViewModel());

    }

    private CarrinhoViewModel GetCarrinhoViewModel()
    {
      List<ItemPedido> itensCarrinho = new List<ItemPedido>
      {
        new ItemPedido(1,produtos[0],1,produtos[0].Preco),
        new ItemPedido(2,produtos[1],2,produtos[1].Preco),
        new ItemPedido(3,produtos[2],3,produtos[2].Preco)
      };

      return new CarrinhoViewModel(itensCarrinho);
    }

    public IActionResult Resumo()
    {
      return View(GetCarrinhoViewModel());

    }
  }
}

CasaCodigoVS/CasaCodigoVS/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CasaCodigoVS/CasaCodigoVS/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CasaCodigoVS/CasaCodigoVS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CasaCodigoVS/CasaCodigoVS/Views/Pedido/Carrinho.cshtml
@{
  ViewData["Title"] = "Carrinho";
}

@model CasaCodigoVS.Models.ViewModels.CarrinhoViewModel
<h3>Meu carrinho</h3>

<div class="panel panel-default">
    <div class="panel-heading">

        <div class="row">
            <div class="col-md-6 text-center">Item</div>
            <div class="col-md-2 text-center">Preço</div>
            <div class="col-md-2 text-center">Quantidade</div>
            <div class="col-md-2">
                <span class="pull-right">Sub-total</span>
            </div>
        </div>

    </div>
    <div class="panel-body">

        @foreach (var itemPedido in Model.Itens)
        {
        <div class="row" style="display:flex; align-items:center">
            <div class="col-md-3">
                <img src="~/images/Produtos/small_@(itemPedido.Id).jpg" />
            </div>
            <div class="col-md-3 text-center">@(itemPedido.Produto.Nome)</div>
            <div class="col-md-2 text-center">R$ @(itemPedido.PrecoUnitario)</div>
            <div class="col-md-2 text-center">@(itemPedido.Quantidade)</div>
            <div class="col-md-2">
                <span class="pull-right"> R$ @(itemPedido.Subtotal) </span>
            </div>
        </div>
        }



        <div class="panel-footer">
            <div class="row">
                <div class="col-md-10">
                    @*Total: @Model.Count() @Html.Raw(@Model.Count() == 1 ? "item" : "itens")*@
                    <span>
                        Total de itens: @Model.Itens.Count() @(Model.Itens.Count == 1 ? "item" : "itens")
                    </span>

                </div>
                <div class="col-md-2">
                    <span class="pull-right">Preço total: R$ @Model.Total</span>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12">

        @*@Html.ActionLink("Finalizar pedido", "resumo", "pedido", null, new { @class = "btn btn-success pull-right" })*@
        @*<a href="/pedido/resumo" class="btn btn-success pull-right">Finalizar pedido</a>*@
        <a asp-controller="pedido" asp-action="resumo" class="btn btn-success pull-right">Adicionar</a>
    </div>
</div>

CasaCodigoVS/CasaCodigoVS/Views/Pedido/Carrossel.cshtml
@{
  ViewData["Title"] = "Carrossel";
}

<h1>Carrossel View</h1>
<div id="my-carousel" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">


        <div class="item active">
            <div class="row">
                @for (int i = 0; i < 4; i++)
                {
                <div class="col-md-3">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <img src="~/images/Produtos/large_@(Model[i].Id).jpg" />
                        </div>
                        <div class="panel-footer">
                            <div>@(Model[i].Nome)</div>
                            <div>R$ @(Model[i].Preco)</div>
                            <div class="text-center">
                                <a asp-controller="pedido" asp-action="carrinho">Adicionar</a>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
        <div class="item">
            <div class="row">
                @for (int i = 4; i < 8; i++)
                {
                <div class="col-md-3">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <img src="~/images/Produtos/large_@(Model[i].Id).jpg" />
                        </div>
                        <div class="panel-footer">
                            <div>@(Model[i].Nome)</div>
                            <div>R$ @(Model[i].Preco)</div>
                            <div class="text-center">
                                <a asp-controller="pedido" asp-action="carrinho">Adicionar</a>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
        <div class="item">
            <div class="row">
                @for (int i = 8; i < 9; i++)
                {
                <div class="col-md-3">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <img src="~/images/Produtos/large_@(Model[i].Id).jpg" />
                        </div>
                        <div class="panel-footer">
                            <div>@(Model[i].Nome)</div>
                            <div>R$ @(Model[i].Preco)</div>
                            <div class="text-center">
                                <a asp-controller="pedido" asp-action="carrinho">Adicionar</a>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>

    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

CasaCodigoVS/CasaCodigoVS/Views/Pedido/Resumo.cshtml
@{
  ViewData["Title"] = "Resumo";
}

@model CasaCodigoVS.Models.ViewModels.CarrinhoViewModel
<h3>View de Resumo</h3>

<div class="panel panel-default">
    <div class="panel-heading"></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <h3>
                    Nº do pedido: 12345678
                </h3>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <h3>Seus dados</h3>
                <div>João da Silva</div>
                <div>(31) 99999-9987</div>
            </div>
            <div class="col-md-3">
                brenojab@gmail.com
            </div>
            <div class="col-md-6">
                <h3>Endereço de entrega</h3>
                <div>Rua Teste, 123</div>
            </div>
            <div class="col-md-6"></div>
        </div>
        <hr />


        <div class="row">
            <div class="col-md-10">
                <h3>Item</h3>
            </div>
            <div class="col-md-2">
                <h3>Quatidade</h3>
            </div>
        </div>

        @foreach (var item in Model.Itens)
        {
          <div class="row">
            <div class="col-md-10">
                <div>@item.Produto.Nome</div>
            </div>
            <div class="col-md-2">
                <div class="pull-right">@item.Quantidade</div>
            </div>
        </div>
        }
    </div>
</div>

CasaCodigoVS/CasaCodigoVS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Casa do Código</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Pedido" asp-action="Carrossel" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Casa do Código</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>